FROM ubuntu:18.04

RUN apt update -y && apt install -y build-essential cmake
RUN apt update -y && apt install -y git curl wget unzip zsh
RUN apt update -y && apt install -y python python-dev python-pip
RUN apt update -y && apt install -y python3 python3-dev python3-pip
